import * as THREE from 'three';
import './style.css';
const texts={tr:{create:'Yeni arkadaşını bul',intro:'Karakterini seç, köpeği yakala ve köpüklerle temizle!',name:'Oyuncu adı',gender:'Karakter',girl:'Kız',boy:'Erkek',hair:'Saç',shirt:'Kıyafet',accessory:'Aksesuar',none:'Yok',hat:'Şapka',start:'Maceraya başla',chase:'Köpeği takip et!',chaseHelp:'WASD / ok tuşlarıyla koş. Yaklaşınca yakalama düğmesine bas.',catch:'Yakala',timing:'Doğru anda yakala!',timingHelp:'İşaret yeşil alandayken bas.',tap:'Şimdi!',wash:'Köpük zamanı',washHelp:'Baloncukları sürükleyip köpeğin üzerine bırak. Beklersen sabrı azalır!',patience:'Rahatlık',clean:'Temizlik',escaped:'Köpek parka kaçtı! Yeniden yakala; bu yıkamayı tekrar deneyeceğiz.',done:'Harika bir başlangıç!',doneHelp:'Yeni arkadaşın tertemiz! Fön, tüy kesimi ve giydirme sonraki sürümde.',again:'Yeniden oyna',near:'Biraz daha yaklaş',saved:'En iyi sonuç',move:'Hareket',pause:'Duraklat',resume:'Devam',paused:'Mola zamanı'},en:{create:'Find your new friend',intro:'Choose your character, catch the puppy and wash with bubbles!',name:'Player name',gender:'Character',girl:'Girl',boy:'Boy',hair:'Hair',shirt:'Outfit',accessory:'Accessory',none:'None',hat:'Hat',start:'Start adventure',chase:'Follow the puppy!',chaseHelp:'Run with WASD / arrow keys. Get close and press Catch.',catch:'Catch',timing:'Catch at the right moment!',timingHelp:'Press when the marker is in the green area.',tap:'Now!',wash:'Bubble time',washHelp:'Drag bubbles onto the puppy. Waiting reduces comfort!',patience:'Comfort',clean:'Cleanliness',escaped:'The puppy ran to the park! Catch again and retry this wash.',done:'A lovely beginning!',doneHelp:'Your new friend is clean! Drying, grooming and dressing come in a later version.',again:'Play again',near:'Get a little closer',saved:'Best result',move:'Move',pause:'Pause',resume:'Resume',paused:'Break time'},de:{create:'Finde deinen neuen Freund',intro:'Wähle deine Figur, fange den Hund und wasche ihn mit Seifenblasen!',name:'Spielername',gender:'Figur',girl:'Mädchen',boy:'Junge',hair:'Haare',shirt:'Kleidung',accessory:'Accessoire',none:'Keins',hat:'Hut',start:'Abenteuer starten',chase:'Folge dem Hund!',chaseHelp:'Laufe mit WASD / Pfeiltasten. Geh näher und drücke Fangen.',catch:'Fangen',timing:'Fange im richtigen Moment!',timingHelp:'Drücke, wenn die Markierung im grünen Bereich ist.',tap:'Jetzt!',wash:'Seifenblasenzeit',washHelp:'Ziehe die Seifenblasen auf den Hund. Beim Warten sinkt sein Wohlbefinden!',patience:'Wohlbefinden',clean:'Sauberkeit',escaped:'Der Hund ist in den Park gelaufen! Fange ihn erneut und wiederhole die Wäsche.',done:'Ein toller Anfang!',doneHelp:'Dein neuer Freund ist sauber! Föhnen, Fellpflege und Anziehen kommen später.',again:'Erneut spielen',near:'Geh etwas näher',saved:'Bestes Ergebnis',move:'Bewegen',pause:'Pause',resume:'Weiter',paused:'Zeit für eine Pause'}};
let lang='tr',stage='create',paused=false,clean=0,comfort=100,misses=0,marker=0,angle=0,elapsed=0,bubbles=[],selectedBubble=null;
const t=k=>texts[lang][k];
const app=document.querySelector('#app');
app.innerHTML=`<canvas id="world"></canvas><header><strong>🐾 World Pet Wash <small>PROTOTİP · 01</small></strong><div><select id="language" aria-label="Language"><option value="tr">Türkçe</option><option value="en">English</option><option value="de">Deutsch</option></select><button id="pause">Ⅱ</button></div></header><div id="panel"></div><div id="hud"></div><div id="controls"><div id="pad"><button data-dir="up">▲</button><div><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div></div><button id="action"></button></div><div id="toast" role="status"></div><div id="bubble-layer"></div><footer>World Pet Wash · browser prototype</footer>`;
const canvas=document.querySelector('#world'),panel=document.querySelector('#panel'),hud=document.querySelector('#hud'),action=document.querySelector('#action'),layer=document.querySelector('#bubble-layer');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.setClearColor('#b8e5ec');
const scene=new THREE.Scene();scene.fog=new THREE.Fog('#b8e5ec',35,75);const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,150);
scene.add(new THREE.HemisphereLight(0xffffff,0x7e9763,2.5));const sun=new THREE.DirectionalLight(0xfff3d9,3);sun.position.set(8,18,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30});scene.add(sun);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.8});
function mesh(geo,color,parent,x=0,y=0,z=0){const m=new THREE.Mesh(geo,mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
const sphere=(r,c,p,x,y,z)=>mesh(new THREE.SphereGeometry(r,16,12),c,p,x,y,z);
const box=(w,h,d,c,p,x,y,z)=>mesh(new THREE.BoxGeometry(w,h,d),c,p,x,y,z);
const park=new THREE.Group();scene.add(park);mesh(new THREE.CylinderGeometry(27,27,1,64),'#9ecb72',park,0,-.55,0);mesh(new THREE.CylinderGeometry(10,10,.03,64),'#e4d3ab',park,0,.01,0);
for(let i=0;i<30;i++){const a=i/30*Math.PI*2,r=20+(i%3);const tree=new THREE.Group();tree.position.set(Math.sin(a)*r,0,Math.cos(a)*r);park.add(tree);mesh(new THREE.CylinderGeometry(.18,.3,2.5,8),'#99775b',tree,0,1.25,0);sphere(1.8,i%2?'#5d9e68':'#73b57b',tree,0,3.3,0);}
for(let i=0;i<45;i++){const a=i*2.4,r=11+(i%8);sphere(.12,['#fff5ce','#f79caf','#b49de2'][i%3],park,Math.sin(a)*r,.12,Math.cos(a)*r);}
box(6,4,4,'#f5e6d2',park,-13,2,-10);mesh(new THREE.ConeGeometry(5,2,4),'#dd8971',park,-13,5,-10).rotation.y=Math.PI/4;box(1.4,2.3,.1,'#79b8c1',park,-13,1.15,-7.95);
const clinic=new THREE.Group();scene.add(clinic);clinic.visible=false;box(20,.3,20,'#d7e5e3',clinic,0,-.2,0);box(20,8,.3,'#f9f1e7',clinic,0,4,-5);box(.3,8,16,'#f0dfd2',clinic,-8,4,0);box(5,.7,3,'#7eb4b9',clinic,0,.35,0);box(5.2,.2,3.2,'#f9ffff',clinic,0,.8,0);box(1.2,.25,.1,'#ec938b',clinic,0,4,-4.8);box(.25,1.2,.1,'#ec938b',clinic,0,4,-4.8);
const player=new THREE.Group();scene.add(player);const shirt=box(.65,.8,.4,'#ec987e',player,0,1.1,0);sphere(.35,'#f4c3a0',player,0,1.85,0);const hair=sphere(.37,'#603f30',player,0,2,0);hair.scale.y=.65;const hat=mesh(new THREE.CylinderGeometry(.48,.48,.15,20),'#f1d47b',player,0,2.2,0);hat.visible=false;const legs=[box(.2,.65,.23,'#456279',player,-.18,.4,0),box(.2,.65,.23,'#456279',player,.18,.4,0)];box(.18,.65,.2,'#f4c3a0',player,-.47,1.1,0);box(.18,.65,.2,'#f4c3a0',player,.47,1.1,0);
const dog=new THREE.Group();scene.add(dog);const coat='#bc875d';const body=sphere(.62,coat,dog,0,.75,0);body.scale.set(.7,.8,1.35);sphere(.43,coat,dog,0,1.05,.75);sphere(.25,'#e5c7a2',dog,0,.9,1.08);sphere(.1,'#403a3c',dog,0,.98,1.29);for(const s of [-1,1]){sphere(.055,'#302e35',dog,s*.19,1.16,1.09);const ear=sphere(.24,'#895a42',dog,s*.37,1.05,.68);ear.scale.set(.6,1.7,.7);for(const z of [-.5,.5])box(.15,.5,.18,coat,dog,s*.3,.28,z);}const tail=box(.14,.14,.7,coat,dog,0,.95,-.94);tail.rotation.x=-.6;const collar=mesh(new THREE.TorusGeometry(.28,.06,8,20),'#70b8bd',dog,0,.95,.49);const dirt=[];for(let i=0;i<8;i++)dirt.push(sphere(.13,'#796c51',dog,(i%2?.35:-.35),.9+(i%3)*.08,-.6+i*.15));
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
const keys=new Set();addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.target.matches('input,select'))return;keys.add(e.key.toLowerCase());if(e.code==='Space'&&!e.repeat)act();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();if(stage!=='create'&&stage!=='done'){paused=true;renderUI();}});
for(const btn of document.querySelectorAll('[data-dir]')){btn.addEventListener('pointerdown',e=>{btn.setPointerCapture(e.pointerId);keys.add(btn.dataset.dir);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])btn.addEventListener(ev,()=>keys.delete(btn.dataset.dir));}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.textContent='',4500);}
let best=0;try{best=Number(localStorage.getItem('wpw-best'))||0;}catch{}
function renderUI(){document.documentElement.lang=lang;document.querySelector('#pause').textContent=paused?t('resume'):t('pause');document.querySelector('#pause').hidden=stage==='create'||stage==='done';document.querySelector('#controls').style.display=(stage==='chase'||stage==='timing')&&!paused?'flex':'none';layer.hidden=stage!=='wash'||paused;
if(stage==='create'){panel.innerHTML=`<div class="eyebrow">WORLD PET WASH</div><h1>${t('create')}</h1><p>${t('intro')}</p><label>${t('name')}<input id="name" maxlength="20" value="Alex"></label><label>${t('gender')}<select id="gender"><option>${t('girl')}</option><option>${t('boy')}</option></select></label><label>${t('hair')}<select id="hair"><option value="#603f30">●</option><option value="#d4a348">🟡</option><option value="#272b39">⚫</option></select></label><label>${t('shirt')}<select id="shirt"><option value="#ec987e">🟠</option><option value="#7fadd6">🔵</option><option value="#a795cd">🟣</option></select></label><label>${t('accessory')}<select id="hat"><option value="none">${t('none')}</option><option value="hat">${t('hat')}</option></select></label><button class="primary" id="start">${t('start')} →</button>`;panel.className='card creation';hud.innerHTML='';document.querySelector('#hair').onchange=e=>hair.material.color.set(e.target.value);document.querySelector('#shirt').onchange=e=>shirt.material.color.set(e.target.value);document.querySelector('#hat').onchange=e=>hat.visible=e.target.value==='hat';document.querySelector('#gender').onchange=e=>hair.scale.y=e.target.selectedIndex===0?1:.65;document.querySelector('#start').onclick=()=>{misses=0;elapsed=0;enterChase();};return;}
if(paused){panel.className='card centered';panel.innerHTML=`<h1>${t('paused')}</h1><button class="primary" id="resume">${t('resume')}</button>`;document.querySelector('#resume').onclick=()=>{paused=false;renderUI();};return;}
if(stage==='done'){const stars=Math.max(1,3-Math.min(2,misses));best=Math.max(best,stars);try{localStorage.setItem('wpw-best',String(best));}catch{}panel.className='card centered';panel.innerHTML=`<div class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><h1>${t('done')}</h1><p>${t('doneHelp')}</p><p>${t('saved')}: ${'★'.repeat(best)}</p><button class="primary" id="again">${t('again')}</button>`;document.querySelector('#again').onclick=()=>{stage='create';park.visible=true;clinic.visible=false;player.visible=true;dog.position.set(2,0,0);player.position.set(0,0,0);renderUI();};hud.innerHTML='';return;}
panel.className='instructions';panel.innerHTML=`<h2>${t(stage)}</h2><p>${t(stage+'Help')}</p>${stage==='timing'?'<div class="timing-track"><div class="target"></div><i id="marker"></i></div>':''}`;action.textContent=t(stage==='timing'?'tap':'catch');hud.innerHTML=stage==='wash'?`<div>${t('clean')} <progress id="clean" max="100" value="${clean}"></progress></div><div>${t('patience')} <progress id="comfort" max="100" value="${comfort}"></progress></div>`:'';}
function enterChase(){stage='chase';paused=false;park.visible=true;clinic.visible=false;player.visible=true;player.position.set(0,0,0);dog.position.set(0,0,5);angle=0;for(const d of dirt)d.visible=true;clearBubbles();renderUI();}
function act(){if(paused)return;if(stage==='chase'){if(player.position.distanceTo(dog.position)<3){stage='timing';marker=0;renderUI();}else toast(t('near'));}else if(stage==='timing'){if(marker>=.38&&marker<=.62)enterWash();else{misses++;stage='chase';dog.position.add(new THREE.Vector3(2,0,2));toast(t('near'));renderUI();}}}
action.onclick=act;document.querySelector('#pause').onclick=()=>{paused=!paused;keys.clear();renderUI();};document.querySelector('#language').onchange=e=>{lang=e.target.value;renderUI();};
function clearBubbles(){for(const b of bubbles)b.el.remove();bubbles=[];selectedBubble=null;}
function addBubble(){const el=document.createElement('button');el.className='bubble';el.setAttribute('aria-label',t('wash'));el.textContent='◌';const b={el,x:10+Math.random()*80,y:30+Math.random()*45};el.style.left=b.x+'%';el.style.top=b.y+'%';layer.append(el);bubbles.push(b);el.addEventListener('pointerdown',e=>{if(paused)return;el.setPointerCapture(e.pointerId);selectedBubble=b;});el.addEventListener('pointermove',e=>{if(selectedBubble!==b)return;el.style.left=e.clientX+'px';el.style.top=e.clientY+'px';});el.addEventListener('pointerup',e=>{if(selectedBubble!==b)return;selectedBubble=null;const projected=dog.position.clone().add(new THREE.Vector3(0,1,0)).project(camera);const x=(projected.x*.5+.5)*innerWidth,y=(-projected.y*.5+.5)*innerHeight;if(Math.hypot(e.clientX-x,e.clientY-y)<Math.min(innerWidth,innerHeight)*.22){clean=Math.min(100,clean+12.5);comfort=Math.min(100,comfort+8);dirt[Math.min(7,Math.ceil(clean/12.5)-1)].visible=false;el.remove();bubbles=bubbles.filter(v=>v!==b);if(clean===100){stage='done';clearBubbles();renderUI();}else addBubble();}else{el.style.left=b.x+'%';el.style.top=b.y+'%';}});el.addEventListener('pointercancel',()=>{selectedBubble=null;el.style.left=b.x+'%';el.style.top=b.y+'%';});}
function enterWash(){camera.position.set(0,3.6,7);camera.lookAt(0,1.6,0);toast('');stage='wash';clean=0;comfort=100;park.visible=false;clinic.visible=true;player.visible=false;dog.position.set(0,.9,0);dog.rotation.y=.3;clearBubbles();renderUI();for(let i=0;i<5;i++)addBubble();}
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(!paused){elapsed+=dt;if(stage==='chase'){const forward=(keys.has('w')||keys.has('arrowup')||keys.has('up')?1:0)-(keys.has('s')||keys.has('arrowdown')||keys.has('down')?1:0);const turn=(keys.has('a')||keys.has('arrowleft')||keys.has('left')?1:0)-(keys.has('d')||keys.has('arrowright')||keys.has('right')?1:0);angle+=turn*dt*2.2;player.rotation.y=angle;player.position.x+=Math.sin(angle)*forward*dt*5;player.position.z+=Math.cos(angle)*forward*dt*5;if(player.position.length()>24)player.position.setLength(24);legs.forEach((l,i)=>l.rotation.x=forward*Math.sin(elapsed*12+i*Math.PI)*.5);const dest=new THREE.Vector3(Math.sin(elapsed*.35)*7,0,Math.cos(elapsed*.35)*7);const dir=dest.sub(dog.position);if(dir.length()>.2){dog.position.addScaledVector(dir.normalize(),dt*2);dog.rotation.y=Math.atan2(dir.x,dir.z);}dog.position.y=Math.sin(elapsed*14)*.035;action.disabled=player.position.distanceTo(dog.position)>=3;}if(stage==='timing'){marker=(Math.sin(elapsed*3.5)+1)/2;document.querySelector('#marker').style.left=marker*100+'%';action.disabled=false;}if(stage==='wash'){comfort-=dt*3;document.querySelector('#comfort').value=comfort;document.querySelector('#clean').value=clean;if(comfort<=0){misses++;enterChase();toast(t('escaped'));}}tail.rotation.y=Math.sin(elapsed*7)*.35;}
let target,look;if(stage==='chase'||stage==='timing'){target=player.position.clone().add(new THREE.Vector3(-Math.sin(angle)*6,4,-Math.cos(angle)*6));look=player.position.clone().add(new THREE.Vector3(Math.sin(angle)*3,1,Math.cos(angle)*3));}else if(stage==='wash'||stage==='done'){target=new THREE.Vector3(0,3.6,7);look=new THREE.Vector3(0,1.6,0);}else{target=new THREE.Vector3(5,3.5,7);look=new THREE.Vector3(0,1,0);dog.position.set(2,0,0);}camera.position.lerp(target,1-Math.exp(-dt*6));camera.lookAt(look);renderer.render(scene,camera);}
camera.position.set(5,3.5,7);renderUI();loop();
